<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>TaskAutomation</AssemblyName>
    <RootNamespace>TaskAutomation</RootNamespace>
    <Version>1.3.1</Version>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SPTPath Condition="'$(SPTPath)' == ''">C:\SPT</SPTPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>$(SPTPath)\BepInEx\core\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(SPTPath)\BepInEx\core\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Comfort"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Comfort.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="ItemComponent.Types"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\ItemComponent.Types.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Sirenix.Serialization"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.InputLegacyModule"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="spt-common"><HintPath>$(SPTPath)\BepInEx\plugins\spt\spt-common.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="spt-core"><HintPath>$(SPTPath)\BepInEx\plugins\spt\spt-core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="spt-custom"><HintPath>$(SPTPath)\BepInEx\plugins\spt\spt-custom.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="spt-reflection"><HintPath>$(SPTPath)\BepInEx\plugins\spt\spt-reflection.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="spt-singleplayer"><HintPath>$(SPTPath)\BepInEx\plugins\spt\spt-singleplayer.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
